const id = (() => {
  let n = 1;
  return () => (n++).toString();
})();

// Use placehold.co for reliable placeholder images during development
const IMG = {
  hoodie: 'https://placehold.co/800x1000?text=Hoodie',
  streetwear: 'https://placehold.co/800x1000?text=Streetwear',
  fashion: 'https://placehold.co/800x1000?text=Fashion',
  men: 'https://placehold.co/800x1000?text=Men+Fashion',
  accessories: 'https://placehold.co/800x1000?text=Accessories',
  women: 'https://placehold.co/800x1000?text=Women+Style',
};

export const FEATURED_PRODUCTS_MOCK = [
  {
    id: id(),
    name: 'Norse Wisdom Runes Hoodie',
    slug: 'norse-wisdom-runes-hoodie',
    price: 249,
    regularPrice: 279,
    categories: ['Men', 'Featured Products'],
  image: { sourceUrl: IMG.hoodie },
  },
  {
    id: id(),
    name: 'Veil of the Valkyrie Tee',
    slug: 'veil-of-the-valkyrie-tee',
    price: 199,
    regularPrice: 219,
    categories: ['Women', 'Featured Products'],
    image: { sourceUrl: IMG.streetwear },
  },
  {
    id: id(),
    name: 'Life Is Tuff Darlin Tee',
    slug: 'life-is-tuff-darlin-tee',
    price: 199,
    regularPrice: 199,
    categories: ['Women'],
  image: { sourceUrl: IMG.fashion },
  },
  {
    id: id(),
    name: 'Urban Street Jacket',
    slug: 'urban-street-jacket',
    price: 229,
    regularPrice: 269,
    categories: ['Men', 'Featured Products'],
  image: { sourceUrl: IMG.men },
  },
  {
    id: id(),
    name: 'Essential Accessories Pack',
    slug: 'essential-accessories-pack',
    price: 89,
    regularPrice: 99,
    categories: ['Accessories', 'Featured Products'],
  image: { sourceUrl: IMG.accessories },
  },
  {
    id: id(),
    name: 'Women Style Classic',
    slug: 'women-style-classic',
    price: 159,
    regularPrice: 179,
    categories: ['Women', 'Featured Products'],
  image: { sourceUrl: IMG.women },
  },
  // — Mysticism-themed additions aligned with navigation (Men / Women / Accessories / Mystical Home)
  {
    id: id(),
    name: 'Triple Moon Rune Tee (Men)',
    slug: 'triple-moon-rune-tee-men',
    price: 199,
    regularPrice: 219,
  categories: ['Men'],
  image: { sourceUrl: IMG.men },
  },
  {
    id: id(),
    name: 'Shaman Spirit Hoodie (Men)',
    slug: 'shaman-spirit-hoodie-men',
    price: 249,
    regularPrice: 279,
  categories: ['Men'],
  image: { sourceUrl: IMG.hoodie },
  },
  {
    id: id(),
    name: 'Runic Shield Sweatshirt (Men)',
    slug: 'runic-shield-sweatshirt-men',
    price: 229,
    regularPrice: 259,
  categories: ['Men'],
  image: { sourceUrl: IMG.men },
  },
  {
    id: id(),
    name: 'Ravenflight Storm Jacket (Men)',
    slug: 'ravenflight-storm-jacket-men',
    price: 279,
    regularPrice: 319,
  categories: ['Men', 'Featured Products'],
  image: { sourceUrl: IMG.men },
  },
  {
    id: id(),
    name: 'Lunar Goddess Tee (Women)',
    slug: 'lunar-goddess-tee-women',
    price: 199,
    regularPrice: 219,
  categories: ['Women'],
  image: { sourceUrl: IMG.women },
  },
  {
    id: id(),
    name: 'Forest Witch Hoodie (Women)',
    slug: 'forest-witch-hoodie-women',
    price: 249,
    regularPrice: 279,
  categories: ['Women'],
  image: { sourceUrl: IMG.women },
  },
  {
    id: id(),
    name: 'White Magic Sigil Sweatshirt (Women)',
    slug: 'white-magic-sigil-sweatshirt-women',
    price: 229,
    regularPrice: 259,
  categories: ['Women'],
  image: { sourceUrl: IMG.women },
  },
  {
    id: id(),
    name: 'Starlight Aegis Jacket (Women)',
    slug: 'starlight-aegis-jacket-women',
    price: 279,
    regularPrice: 319,
  categories: ['Women'],
  image: { sourceUrl: IMG.women },
  },
  {
    id: id(),
    name: 'Pentacle Crest Cap',
    slug: 'pentacle-crest-cap',
    price: 59,
    regularPrice: 69,
  categories: ['Accessories'],
  image: { sourceUrl: IMG.accessories },
  },
  {
    id: id(),
    name: 'Elder Rune Beanie',
    slug: 'elder-rune-beanie',
    price: 49,
    regularPrice: 59,
  categories: ['Accessories'],
  image: { sourceUrl: IMG.accessories },
  },
  {
    id: id(),
    name: 'Cauldron Blessing Mug',
    slug: 'cauldron-blessing-mug',
    price: 29,
    regularPrice: 39,
  categories: ['Accessories'],
  image: { sourceUrl: IMG.accessories },
  },
  {
    id: id(),
    name: 'Moon Phase Water Bottle',
    slug: 'moon-phase-water-bottle',
    price: 35,
    regularPrice: 45,
  categories: ['Accessories'],
  image: { sourceUrl: IMG.accessories },
  },
  // Additional items to reach 30 total
  {
    id: id(),
    name: 'Mystic Compass Necklace',
    slug: 'mystic-compass-necklace',
    price: 39,
    regularPrice: 49,
    categories: ['Accessories', 'Featured Products'],
    image: { sourceUrl: IMG.accessories },
  },
  {
    id: id(),
    name: 'Ironwood Totem Bracelet',
    slug: 'ironwood-totem-bracelet',
    price: 45,
    regularPrice: 55,
    categories: ['Accessories'],
    image: { sourceUrl: IMG.accessories },
  },
  {
    id: id(),
    name: 'Astral Path Pendant',
    slug: 'astral-path-pendant',
    price: 49,
    regularPrice: 59,
    categories: ['Accessories'],
    image: { sourceUrl: IMG.accessories },
  },
  {
    id: id(),
    name: 'Valkyrie Trail Boots (Men)',
    slug: 'valkyrie-trail-boots-men',
    price: 199,
    regularPrice: 239,
    categories: ['Men'],
    image: { sourceUrl: IMG.men },
  },
  {
    id: id(),
    name: "Berserker Training Joggers (Men)",
    slug: 'berserker-training-joggers-men',
    price: 129,
    regularPrice: 149,
    categories: ['Men'],
    image: { sourceUrl: IMG.men },
  },
  {
    id: id(),
    name: "Odin's Ravens Tee (Men)",
    slug: 'odins-ravens-tee-men',
    price: 189,
    regularPrice: 209,
    categories: ['Men', 'Featured Products'],
    image: { sourceUrl: IMG.men },
  },
  {
    id: id(),
    name: 'Seidr Dream Cloak (Women)',
    slug: 'seidr-dream-cloak-women',
    price: 259,
    regularPrice: 299,
    categories: ['Women'],
    image: { sourceUrl: IMG.women },
  },
  {
    id: id(),
    name: 'Moonweaver Cardigan (Women)',
    slug: 'moonweaver-cardigan-women',
    price: 189,
    regularPrice: 219,
    categories: ['Women'],
    image: { sourceUrl: IMG.women },
  },
  {
    id: id(),
    name: 'Aurora Hex Skirt (Women)',
    slug: 'aurora-hex-skirt-women',
    price: 139,
    regularPrice: 159,
    categories: ['Women'],
    image: { sourceUrl: IMG.women },
  },
  {
    id: id(),
    name: 'Witchlight Pocket Tee (Women)',
    slug: 'witchlight-pocket-tee-women',
    price: 129,
    regularPrice: 149,
    categories: ['Women'],
    image: { sourceUrl: IMG.women },
  },
  {
    id: id(),
    name: 'Runebound Travel Pack',
    slug: 'runebound-travel-pack',
    price: 119,
    regularPrice: 139,
    categories: ['Accessories'],
    image: { sourceUrl: IMG.accessories },
  },
  {
    id: id(),
    name: 'Starforge Trucker Cap',
    slug: 'starforge-trucker-cap',
    price: 39,
    regularPrice: 49,
    categories: ['Accessories'],
    image: { sourceUrl: IMG.accessories },
  },
];
